package LeetCodeEasyString;
import java.util.HashMap;
// You are given two strings s and t.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.
// Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
public class Leet389 {
    public static char findTheDifference(String s, String t) {
        HashMap<Integer,Character> hm = new HashMap<Integer,Character>();
        for(int i = 0; i < s.length(); i++){
            hm.put(i,s.charAt(i));
        }
        for(int i = 0; i < t.length(); i++){
            if(!hm.containsValue(t.charAt(i))) return t.charAt(i);
            continue;
        }
        return '/';
    }

    public static void main(String[] args) {
        String a = "a";
        String b = "aa";
        System.out.println(findTheDifference(a,b));
    }
}
